### ISSUE TITLE
Possible improvement to random shortcut folders

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/tikipeter.github.io#98]
Hey Peter,

Sorry to bother you again. I've been playing around with the new random shortcuts feature you added and so far it's been a decent replacement to autowidget, which is the addon I was using for this same function in the past. I have 8 folders created, each containing around 10-12 trakt lists which randomly rotate on my homescreen as widgets.

The only problem I'm facing with them is they will refresh if you do virtually anything with the items they contain e.g. Play a trailer or mark as watched / unwatched. I'm aware that this is not necessarily a problem with fen, but rather kodi itself. With that being said though, the reason I mentioned autowidget is because that addon handles refreshing differently. It's timer based, and only refreshes based on the time set by you. Playback does not force a refresh, nor does anything else. It's purely based on the time you set. 
This is how the settings look:

![20240823_144929.jpg](https://github.com/user-attachments/assets/38c66a0e-32c7-4551-91f3-7597f51d1de3)

I think it would be a better browsing experience if we could set the frequency of the random shortcut folders to refresh at a specified time rather then the same time as the other generic lists. That way, I could browse though my homescreen and add / remove things from my watchlists without worrying about everything refreshing. It seems drinfernoo (autowidget dev) figured out a way around this refreshing problem. Maybe you could take a look at his code and possibly incorporate something similar to Fen Light? 

I just thought I'd bring this to your attention incase you were thinking of possible ways to improve on the random shortcut folders. Also, thanks a lot for adding the MPAA regions.

**Comment by Tikipeter** [comment]
There's absolutely no way to stop Kodi refreshing the widgets when it wants to, so he must be keeping the current path and reloading that outside of the alloted times.

Let me think on it....

**Comment by Tikipeter** [comment]
Progress is slow due to my limited time, but is being made on this front.

**Comment by rizreflects** [comment]
Take your time, no rush.

**Comment by Tikipeter** [comment]
Done for next update.

**Comment by rizreflects** [comment]
That was very fast. I look forward to testing this out.

**Comment by rizreflects** [comment]
Hey Peter,

Sorry to bother you with this, but I just updated to v1.0.74 and I'm struggling to get the 'refresh widgets on timer' option to work. I have it set for every 2 hours, but when I play a trailer my widgets are still refreshing. I use the random shortcut folders function, and the list I'm currently viewing will refresh to a new list each time I play a trailer. I'm not sure what I'm doing wrong. My assumption was the list I'm viewing would remain even after a trailer is played.

**Comment by rizreflects** [comment]
Hey Peter, I don't mean to push you or anything, but are anymore updates planned for the shortcut folders? They're still not reloading based on their timer at all for me. I tested this on a libreelec device as well as my usual android device and it doesn't function correctly on either. I've gone back to autowidget which works fine for now, but I'd ideally like to update to arctic fuse 2 once it's released, however autowidget doesn't work on any of the newer skins like fuse or nimbus. So that's why I was hoping to get this issue resolved before then. If no further updates are planned that's fine by me though. I'll be here to test if needed.

Thanks a lot
